### ISSUE TITLE
Work around on windows.

### ISSUE THREAD

**Issue by nikhil-above** [creckx/InvoiceGenerator#16]
On windows it gives 2 error,
1) Not able to find DejaVu.ttf font
2) Not able to set locale.

To solve first you have to replace DejaVu with Vera (default font in reportlab) & DejaVu-Bold with VeraBd. Update FONT_PATH in `conf.py`. Point it towards `Vera.ttf` under reportlab directory.

For second, you have to change in pdf.py in line 69,
 `locale.setlocale(locale.LC_ALL, str('american'))`
Locale setting is mess on windows. To select any other locale setting put `Language String` from https://msdn.microsoft.com/en-us/library/39cwe7zf(vs.71).aspx

**Comment by PetrDlouhy** [comment]
The locale problem could be fixed in PR #20

**Comment by PetrDlouhy** [comment]
This is long time without reply. I am closing this. If this is still a problem, please reopen.
