### ISSUE TITLE
Example should have `import os`

### ISSUE THREAD

**Issue by lolobosse** [creckx/InvoiceGenerator#26]
I know that this is trivial but I hate examples not working out of the box 😉

**Comment by PetrDlouhy** [comment]
I addressed this issue in #28 which also contains large documentation improvements.

**Comment by shaun-ba** [comment]
@PetrDlouhy Why not build for PIP if there are known issues? Sure, your latest code won't be stable, but neither is 0.5.4 :)

**Comment by PetrDlouhy** [comment]
@shaun-ba I am not maintainer of this repository, so this question goes to @creckx 

You have to clone my repository at branch `feature/pohoda`: https://github.com/PetrDlouhy/InvoiceGenerator/tree/feature/pohoda

**Comment by shaun-ba** [comment]
hi @PetrDlouhy yes i've since realised, and have cloned your fork, thank you for putting the work into it and the documentation.

**Comment by PetrDlouhy** [comment]
Now I can maintain this repository, so it is merged.
